#PBS -N copro_test
#PBS -j oe
#PBS -m abe
#PBS -M mvanmoer@illinois.edu
#PBS -l ncpus=8
#PBS -l mem=16GB
#PBS -l walltime=00:30:00
#PBS -A TG-CTS110010

module load paraview/3.14.1

CELLDIR=/nics/b/home/mvanmoer/projects/muite/NS3D-MPI/cell-based
# if writing images
#cd $PBS_O_WORKDIR

cd ${CELLDIR}

# if writing data files, will exceed $HOME quota
# cd $SCRATCHDIR
ulimit -s unlimited
mpiexec ${CELLDIR}/ns3d-pvcp-cells
exit
